# Generated by Django 5.2.11 on 2026-02-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='证书图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='遵盛汽车零部件有限公司', max_length=100, verbose_name='公司名称')),
                ('short_name', models.CharField(default='遵盛', max_length=20, verbose_name='简称')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='标语')),
                ('description', models.TextField(verbose_name='公司简介')),
                ('image', models.ImageField(blank=True, upload_to='company/', verbose_name='公司图片')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
            ],
            options={
                'verbose_name': '客户留言',
                'verbose_name_plural': '客户留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover', models.ImageField(blank=True, upload_to='news/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.newscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称/型号')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('image', models.ImageField(upload_to='products/', verbose_name='产品图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.productcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'ordering': ['order'],
            },
        ),
    ]
