# Generated by Django 5.2.11 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_banner',
            field=models.ImageField(blank=True, help_text='如果不上传，将显示默认颜色背景', upload_to='company/', verbose_name='关于页面Banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_slogan_cn',
            field=models.CharField(default='造一流汽配产品，铸宏博顶级品牌', max_length=200, verbose_name='关于页面标语(中)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_slogan_en',
            field=models.CharField(default='MAKE FIRST-CLASS AUTO PARTS, CAST HAWBO TOP BRAND', max_length=200, verbose_name='关于页面标语(英)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='首页标语'),
        ),
    ]
