# Generated by Django 5.2.11 on 2026-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_companyinfo_about_banner_companyinfo_about_slogan_cn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('image', models.ImageField(upload_to='environment/', verbose_name='环境图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '公司环境',
                'verbose_name_plural': '公司环境管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='设备图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '技术设备',
                'verbose_name_plural': '技术设备管理',
                'ordering': ['order'],
            },
        ),
    ]
