# Generated by Django 5.2.11 on 2026-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_companyenvironment_technicalequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='news_banner',
            field=models.ImageField(blank=True, upload_to='company/', verbose_name='新闻页面Banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='news_slogan_cn',
            field=models.CharField(default='互补、团结和谐并为负有共同责任', max_length=200, verbose_name='新闻页面标语(中)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='news_slogan_en',
            field=models.CharField(default='TO COMPLEMENT EACH OTHER, UNITY AND HARMONY AND BEAR THE COMMON RESPONSIBILITY', max_length=200, verbose_name='新闻页面标语(英)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_slogan_cn',
            field=models.CharField(default='造一流汽配产品，铸遵盛顶级品牌', max_length=200, verbose_name='关于页面标语(中)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_slogan_en',
            field=models.CharField(default='MAKE FIRST-CLASS AUTO PARTS, CAST ZUNSHENG TOP BRAND', max_length=200, verbose_name='关于页面标语(英)'),
        ),
    ]
