# Generated by Django 5.2.11 on 2026-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_companyinfo_news_banner_companyinfo_news_slogan_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='product_banner',
            field=models.ImageField(blank=True, upload_to='company/', verbose_name='产品页面Banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='product_slogan_cn',
            field=models.CharField(default='注重产品质量，降低生产成本', max_length=200, verbose_name='产品页面标语(中)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='product_slogan_en',
            field=models.CharField(default='FOCUS ON PRODUCT QUALITY AND REDUCE PRODUCTION COSTS', max_length=200, verbose_name='产品页面标语(英)'),
        ),
    ]
