# Generated by Django 5.2.11 on 2026-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_companyinfo_product_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='service_banner',
            field=models.ImageField(blank=True, upload_to='company/', verbose_name='服务页面Banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='service_slogan_cn',
            field=models.CharField(default='你的需求，我们的追求，宏博汽配', max_length=200, verbose_name='服务页面标语(中)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='service_slogan_en',
            field=models.CharField(default='YOUR NEEDS, OUR PURSUIT, HAWBO AUTO PARTS', max_length=200, verbose_name='服务页面标语(英)'),
        ),
    ]
