# Generated by Django 5.2.11 on 2026-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_companyinfo_service_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='contact_banner',
            field=models.ImageField(blank=True, upload_to='company/', verbose_name='联系页面Banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='contact_slogan_cn',
            field=models.CharField(default='你的关注是我的动力，遵盛竭诚为你服务', max_length=200, verbose_name='联系页面标语(中)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='contact_slogan_en',
            field=models.CharField(default='YOUR ATTENTION IS OUR MOTIVATION, ZUNSHENG IS AT YOUR SERVICE', max_length=200, verbose_name='联系页面标语(英)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='service_slogan_cn',
            field=models.CharField(default='你的需求，我们的追求，遵盛汽配', max_length=200, verbose_name='服务页面标语(中)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='service_slogan_en',
            field=models.CharField(default='YOUR NEEDS, OUR PURSUIT, ZUNSHENG AUTO PARTS', max_length=200, verbose_name='服务页面标语(英)'),
        ),
    ]
