# Generated by Django 5.2.11 on 2026-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_companyinfo_contact_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='证书名称(英)'),
        ),
        migrations.AddField(
            model_name='companyenvironment',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='环境名称(英)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址(英)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='公司简介(英)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='副标题(英)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题(英)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='内容(英)'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='摘要(英)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='标题(英)'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='分类名称(英)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='产品描述(英)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='产品名称/型号(英)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='分类名称(英)'),
        ),
        migrations.AddField(
            model_name='technicalequipment',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备名称(英)'),
        ),
    ]
