# Generated by Django 5.2.11 on 2026-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_certificate_name_en_companyenvironment_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='pdf_catalog',
            field=models.FileField(blank=True, null=True, upload_to='company/', verbose_name='电子图册(PDF)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='wechat_qr',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='微信二维码'),
        ),
    ]
